upstream accounts_service {
    server servify-accounts:8001;
}

upstream services_service {
    server servify-services:8002;
}

upstream bookings_service {
    server servify-bookings:8003;
}

server {
    listen 80;

    location /api/accounts/ {
        proxy_pass http://accounts_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/services/ {
        proxy_pass http://services_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/bookings/ {
        proxy_pass http://bookings_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
